TurboAPI
TurboWarp/extensions pull request #1010
Opened 2023-09-04 06:25 UTC by Tekinical

Ok 4th attempt, I fixed all lint issues, just prettier wasn't working on the GitHub check so I did it myself!<br>TurboAPI can do POST and GET requests from code blocks.<br>
![Screenshot 2023-09-04 000447](https://github.com/TurboWarp/extensions/assets/140775902/6302479c-9acf-4a99-ae38-1ca5b2e5b7f2)
![real trap sh](https://github.com/TurboWarp/extensions/assets/140775902/e12fdeee-8a5b-4f3c-82a9-b86f70ee6adb)
![New Project (5)](https://github.com/TurboWarp/extensions/assets/140775902/71b6b798-43d8-49a4-a886-3c335b148f0f)
<br>If you wanna try it out now, import it via: http://createserver.xyz/turbowarp/TurboAPI

2023-09-04 06:26 UTC, Tekinical commented
@LilyMakesThings my bad, this is my first time attempting pull requests, had no idea you could re-edit them, next time I will.

2023-09-04 06:35 UTC, GarboMuffin commented
don't close and open a new pull request, just edit the existing pull request, otherwise you are sending us spam

2023-09-04 06:45 UTC, NexusKitten requested changes
Is there any reason to use this over [Network](https://turbowarp.org/editor?extension=https://extensions.turbowarp.org/true-fantom/network.js)? According to CONTRIBUTING.md, extensions that are similar to pre-existing ones are less likely to get accepted, and both blocks in this extension have replicated functionality over there:

![image](https://github.com/TurboWarp/extensions/assets/127152751/93ea67f2-e5f2-492d-8c3d-897bfe676003)

This doesn't mean take down the PR, but it may not be approved due to their similarities.

2023-09-04 06:53 UTC, Tekinical commented on extensions/turboapi.js
> +              "https://freeiconshop.com/wp-content/uploads/edd/download-flat.png",
I'll work on all these changes soon, working on something atm.

2023-09-04 06:59 UTC, Tekinical commented on extensions/turboapi.js
> +        menuIconURI: "https://files.catbox.moe/4eb196.png",
✅

2023-09-04 07:00 UTC, Tekinical commented on extensions/turboapi.js
> +              "https://freeiconshop.com/wp-content/uploads/edd/download-flat.png",
✅

2023-09-04 07:01 UTC, Tekinical commented
@NexusKitten every suggestion you made is now resolved, I'll run it through prettifier then publish it.

2023-09-04 07:11 UTC, Tekinical commented
All changes done, updated the extension (also updated the 3rd party link to the newest version too)

2023-09-04 16:16 UTC, mightbelite commented
I didn't see this comment, sorry. This was my first time making a pull request so I had no idea it could auto-update.

2023-09-04 16:17 UTC, mightbelite commented
> I didn't see this comment, sorry. This was my first time making a pull request so I had no idea it could auto-update.

(This is tekinical on his alt)

2023-09-04 17:03 UTC, Tekinical commented
I'm in the process of updating it to be more lightweight, but for some reason, this doesn't report a value?
![image](https://github.com/TurboWarp/extensions/assets/140775902/90691d0f-10b1-4895-a43d-fdb52a69e024)
![image](https://github.com/TurboWarp/extensions/assets/140775902/8d204163-8588-4bc1-bd68-f1ba3a72bb6d)
![image](https://github.com/TurboWarp/extensions/assets/140775902/eeb5b01b-d047-48d4-8c8a-50b810448303)

2023-09-04 17:39 UTC, CST1229 commented
> I'm in the process of updating it to be more lightweight, but for some reason, this doesn't report a value?

It probably throws an error, and [unsandboxed blocks shouldn't throw.](https://docs.turbowarp.org/development/extensions/unsandboxed#increased-power-brings-increased-responsibility)

2023-09-04 19:14 UTC, Tekinical commented
> > I'm in the process of updating it to be more lightweight, but for some reason, this doesn't report a value?
> 
> It probably throws an error, and [unsandboxed blocks shouldn't throw.](https://docs.turbowarp.org/development/extensions/unsandboxed#increased-power-brings-increased-responsibility)

Already checked and it doesn't. It just simply doesn't report the value.

2023-09-04 19:17 UTC, Tekinical commented
I just wont add this then; I'll figure out something else to make the extension better.

2023-09-04 19:45 UTC, NexusKitten commented
> I'm in the process of updating it to be more lightweight, but for some reason, this doesn't report a value? ![image](https://user-images.githubusercontent.com/140775902/265515041-90691d0f-10b1-4895-a43d-fdb52a69e024.png) ![image](https://user-images.githubusercontent.com/140775902/265515063-8d204163-8588-4bc1-bd68-f1ba3a72bb6d.png) ![image](https://user-images.githubusercontent.com/140775902/265515202-eeb5b01b-d047-48d4-8c8a-50b810448303.png)

You forgot to make the function async

2023-09-04 20:33 UTC, Tekinical commented
> > I'm in the process of updating it to be more lightweight, but for some reason, this doesn't report a value? ![image](https://user-images.githubusercontent.com/140775902/265515041-90691d0f-10b1-4895-a43d-fdb52a69e024.png) ![image](https://user-images.githubusercontent.com/140775902/265515063-8d204163-8588-4bc1-bd68-f1ba3a72bb6d.png) ![image](https://user-images.githubusercontent.com/140775902/265515202-eeb5b01b-d047-48d4-8c8a-50b810448303.png)
> 
> You forgot to make the function async

Thank you, update to the script that makes it more lightweight will be published in a minute.
![image](https://github.com/TurboWarp/extensions/assets/140775902/05fd8a6d-df95-46ed-8eda-30c07b645eca)
![image](https://github.com/TurboWarp/extensions/assets/140775902/ecc53b23-8e45-49b7-916f-213ce05e3d20)

2023-09-04 20:37 UTC, Tekinical commented
Passed all checks! Yippee!

(if anyone wants to try this out, you can copy it here or from my fork. http://createserver.xyz/turbowarp/TurboAPI.js

2023-09-09 03:23 UTC, GarboMuffin commented
please submit exactly 1 extension per pull request

2023-09-09 03:36 UTC, Tekinical commented
> please submit exactly 1 extension per pull request

how do i do that. it automatically put my extension in this pull request

2023-09-09 04:53 UTC, Tekinical commented
! Before commenting on this: I am no longer giving support to this extension unless it gets added to the extension gallery, this was easy to make and I don't wanna add anything else. It's basically fetch but with a post request option. Go check out my Save Codes extension which is much better than this.

2023-09-09 14:06 UTC, closed without merging