Create Sprite Parenting
TurboWarp/extensions pull request #1057
Opened 2023-09-24 16:26 UTC by SharkPool-SP

Extension for Linking Sprites Together!
<img width="600" alt="Screenshot 2023-09-24 at 9 23 29 AM" src="https://github.com/TurboWarp/extensions/assets/139097378/96329129-8693-470b-80a3-8e89aee00241">

2023-09-24 16:52 UTC, CubesterYT commented
LETS GO!! I have some suggestions that I will mention soon.

2023-09-24 16:55 UTC, SharkPool-SP commented
> LETS GO!! I have some suggestions that I will mention soon.

I need to format it still :((((

2023-09-24 16:59 UTC, Tekinical commented
Nice!

2023-09-24 16:59 UTC, SharkPool-SP commented
> Nice!

Thanks!

2023-09-24 20:39 UTC, LilyMakesThings requested changes
A lot of your arguments are used in places where they depend on it being a string, so I advise you go back and cast them all to a string.

2023-09-24 20:39 UTC, LilyMakesThings commented on extensions/SharkPool/Sprite-Parenting.js
> +      this.ogPositions = {};
Please use `Object.create(null)` for all of these.

2023-09-24 20:39 UTC, LilyMakesThings commented on extensions/SharkPool/Sprite-Parenting.js
> +      const linkName = args.LINK;
Cast these to a string

2023-09-24 20:39 UTC, LilyMakesThings commented on extensions/SharkPool/Sprite-Parenting.js
> +      const target = runtime.getSpriteTargetByName(args.NAME);
make sure that it doesn't do anything if there is no target found!

2023-09-24 20:39 UTC, LilyMakesThings commented on extensions/SharkPool/Sprite-Parenting.js
> +      this.links = {};
Please use `Object.create(null)` for all of these.

2023-09-24 20:39 UTC, LilyMakesThings commented on extensions/SharkPool/Sprite-Parenting.js
> +    _getTargets() {
I know this is my code but you can simplify this greatly

2023-09-24 23:38 UTC, SharkPool-SP commented
> A lot of your arguments are used in places where they depend on it being a string, so I advise you go back and cast them all to a string.

Fixed em all

2023-09-25 07:04 UTC, horizontal-shading commented
This extension is making me imagine a conversation like:

"Hey Sprite1?"
"Yes?"
"You're adopted."

2023-09-25 16:17 UTC, SharkPool-SP commented
> This extension is making me imagine a conversation like:
> 
> "Hey Sprite1?" "Yes?" "You're adopted."

Lol

2023-09-25 23:54 UTC, LilyMakesThings approved these changes

2023-11-16 16:28 UTC, BlueDome77 commented
> This extension is making me imagine a conversation like:
> 
> "Hey Sprite1?" "Yes?" "You're adopted."

I was hoping for a Tommyinnit version...

2023-11-16 16:32 UTC, SharkPool-SP commented
> When will this be stable enough to use in projects?

Yep

2024-01-03 04:55 UTC, SharkPool-SP commented
Now Supports Clones!

2024-03-01 07:35 UTC, SharkPool-SP commented
V 2.0 is out, rewrote everything, much better, optimized, and has better sprite support

2025-02-26 19:00 UTC, SharkPool-SP commented
this, to me, is useless. I dont see a use for it in the gallery anymore

2025-02-26 19:00 UTC, closed without merging