Create Today's actual date
TurboWarp/extensions pull request #1182
Opened 2023-12-05 04:59 UTC by aiotv1

Create Today's actual date
Example :
monday , december , 2023 ,24

2023-12-05 05:13 UTC, LilyMakesThings requested changes
Based on the mistakes made, you have clearly not read the [Developer Documentation](https://docs.turbowarp.org/development/extensions/introduction) and the [Contributing Guidelines](https://github.com/TurboWarp/extensions/blob/master/CONTRIBUTING.md) **in full**.

I strongly advise you read those 2 documents before submitting an extension. Particularly pay close attention to [this].(https://github.com/TurboWarp/extensions/blob/master/CONTRIBUTING.md#acceptance-criteria)

2023-12-05 05:13 UTC, LilyMakesThings commented on extensions/Today's actual date
> +class DateTimeExtension {
Extensions that are submitted must be wrapped in an [immediately-invoked-function-expression (IIFE)](https://docs.turbowarp.org/development/extensions/unsandboxed#:~:text=The%20unsandboxed%20version%20would%20have%20code%20like%20this%3A).

2023-12-05 05:13 UTC, LilyMakesThings commented on extensions/Today's actual date
> +      id: 'datetimeexample',
You extension ID must include your name in some form.

2023-12-05 05:13 UTC, LilyMakesThings commented on extensions/Today's actual date
Your extension file must be placed inside a folder with your name and be given the .js file extension.

2023-12-21 06:34 UTC, GarboMuffin commented
see above feedback; please also refrain from relying on ChatGPT too heavily as it doesn't know that much about writing extensions

2023-12-21 06:34 UTC, closed without merging

2023-12-21 07:08 UTC, GarboMuffin commented
I will note that this is easy to port to normal Scratch scripts very directly