New Extension
TurboWarp/extensions pull request #1198
Opened 2023-12-13 16:30 UTC by wolfieboy09

I made an extension that just returns the sprite's costume names.
JSON extension needed, because it returns an array

2023-12-13 16:31 UTC, wolfieboy09 commented
![image](https://github.com/TurboWarp/extensions/assets/105564186/5fd86e59-a492-4a7f-af44-edb41a07cae3)

2023-12-13 16:56 UTC, LilyMakesThings requested changes
I'm not sure if there needs to be an entire extension for a single block

2023-12-13 16:56 UTC, LilyMakesThings commented on extensions/Wolfieboy09/spritecostumes.js
> +				id: 'costumer',
The extension ID must contain your username

2023-12-21 06:02 UTC, GarboMuffin commented
could this be a candidate for asset manager?

@LilyMakesThings

2023-12-21 06:25 UTC, GarboMuffin commented
turns out this will be in Asset Manager *when* it is merged :)

2023-12-21 06:25 UTC, closed without merging