New Array Extension
TurboWarp/extensions pull request #1301
Opened 2024-02-15 22:57 UTC by SpyroStudios

# Arrays Extension

## Overview
This repository contains the code for a new Arrays Extension, which will add support for 2D and 3D arrays in TurboWarp.

## Features
- Create 2D arrays with dimensions
- Set and get values in 2D arrays at specific indices
- Check if a 2D array exists
- Get the row and column count of a 2D array
- Duplicate a 2D array
- Count occurrences of an item in a 2D array
- Create 3D arrays with customizable dimensions
- Set and get values in 3D arrays at specific indices
- Check if a 3D array exists
- Get the row, column, and depth count of a 3D array
- Duplicate a 3D array
- Count occurrences of an item in a 3D array

### Note
- Indices start from 1 instead of 0 to coincide better with vanilla Lists
- An array of a type (2D, 3D) of the same name as another array of that type will overwrite the name of any preexisting array
- 2D arrays and 3D arrays of the same name will not overwrite the other type of array of the same name

2024-02-15 23:10 UTC, LilyMakesThings requested changes
Check the errors; I explained a workaround within one of the comments.

Storing the arrays in the variables of the sprite is a bit unnecessary. Personally I'd just store it within the extension. If you were trying to save to the project, you'd be interested in `vm.runtime.extensionStorage`, but considering the lists are created during runtime, I don't think that would matter.

There doesn't appear to be a way to delete arrays yet.

Format is done on merge, you don't need to worry about that if you don't want to.

2024-02-15 23:10 UTC, LilyMakesThings commented on extensions/SpyroStudios/Arrays.js
> +      return util.target.variables.hasOwnProperty(name);
- Storing onto the variables object of a target is probably not a good idea..
- You can return `!!util.target.variables[name]` for the same result.

2024-02-15 23:10 UTC, LilyMakesThings commented on extensions/SpyroStudios/Arrays.js
> +            text: "in 3D array [NAME] count occurrences of item [ITEM]",
a better way of rewording this would be: `count # of [ITEM] in 3D array [NAME]`

2024-02-15 23:10 UTC, LilyMakesThings commented on extensions/SpyroStudios/Arrays.js
> +                defaultValue: "new_array"
the underscore is a bit unnecessary

2024-02-15 23:10 UTC, LilyMakesThings commented on extensions/SpyroStudios/Arrays.js
> +            hideFromPalette: false
you don't need to tell the labels to not hide from the palette; they show by default anyway

2024-02-16 01:50 UTC, LilyMakesThings commented on extensions/SpyroStudios/Arrays.js
> +      if (!!util.target.variables[name]) {
ok this is my fault; in if statements you don't need the !! because it's already checking a condition

2024-02-23 19:20 UTC, LilyMakesThings approved these changes

2024-10-30 09:56 UTC, Drago-Cuven commented
is it possible for you to make array resizing blocks?

2024-11-04 01:59 UTC, SpyroStudios commented
> is it possible for you to make array resizing blocks? @SpyroStudios ?

Probably, but what would you want me to do if there already are existing values

2024-12-25 00:49 UTC, yuri-kiss commented
> > is it possible for you to make array resizing blocks? @SpyroStudios ?
> 
> Probably, but what would you want me to do if there already are existing values

The values could be discarded.

2024-12-25 00:49 UTC, yuri-kiss commented on extensions/SpyroStudios/Arrays.js
> +
license pleaseee

2024-12-25 00:50 UTC, yuri-kiss commented on extensions/SpyroStudios/Arrays.js
> +      const name = `${args.NAME}_2D`;
Make sure to cast your arguments (this goes for all your blocks)

2025-02-05 00:53 UTC, yuri-kiss commented
Close for being stale.

2025-02-05 00:53 UTC, closed without merging