IndexedDB extension (omg this is like my 3rd try lol)
TurboWarp/extensions pull request #1341
Opened 2024-03-02 21:48 UTC by ffghdfh

lemme in please 🥺

2024-03-02 22:57 UTC, CubesterYT commented
Please don't close and open the PRs. Are you experiencing some kind of problem?

2024-03-02 23:01 UTC, ffghdfh commented
> Please don't close and open the PRs. Are you experiencing some kind of problem?

Oh sh#t sorry, didn't know I shouldn't do that😅
i've just been trying to add my extension and there was always something that came up! But i guess i just gotta play the waiting game...

2024-03-02 23:33 UTC, CST1229 commented
> i've just been trying to add my extension and there was always something that came up! But i guess i just gotta play the waiting game...

Don't expect pull requests to be merged soon; GarboMuffin (TurboWarp's creator) has a job and mostly only is active here on weekends.

2024-03-03 09:40 UTC, ffghdfh commented
> > i've just been trying to add my extension and there was always something that came up! But i guess i just gotta play the waiting game...
> 
> Don't expect pull requests to be merged soon; GarboMuffin (TurboWarp's creator) has a job and mostly only is active here on weekends.

OHHH! I THOUGHT ALL OF Y'ALL WHO COMMENT COULD TOTALLY MERGE IT AND JUST DIDN'T WANT TO 😅
Okay that's good to know, thank you for letting me know about that too! :D

2024-03-03 12:03 UTC, LilyMakesThings requested changes

2024-03-03 12:31 UTC, ffghdfh commented on extensions/ffghdfh/indexedDB.js
> +// Description: Lets you use an IndexedDB database, allowing for you to store more than 5MB of data locally. By chair_senpai.
Okay so i think you probably meant the // By: thingy, sorry for leaving that out, I just went off of the local storage extension which did not have that, oops!

2024-03-03 12:32 UTC, ffghdfh commented on extensions/ffghdfh/indexedDB.js
> +      return this._getValue(KEY);
Okie dokie, changed that too!

2024-03-03 12:33 UTC, ffghdfh reviewed
Changed what y'all asked for!

2024-03-03 14:53 UTC, LilyMakesThings approved these changes, later dismissed

2024-03-16 23:47 UTC, DNin01 commented
I worry that projects might abuse this to take up lots of storage on users' devices, and local storage is fine for the most common use cases. Does IndexedDB have any limits?

2024-03-17 00:15 UTC, CST1229 commented
> I worry that projects might abuse this to take up lots of storage on users' devices, and local storage is fine for the most common use cases. Does IndexedDB have any limits?

https://developer.mozilla.org/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria#other_web_technologies
there is a limit, but it's gigabytes in size (and also browser-dependent)

2024-08-01 11:24 UTC, CubesterYT commented
Hey man! Remember me? I'm a TurboWarp Collaborater now so I can do a full thorough review and revisions on your PR, such as prettier, translation functions, etc. So let me know if your PR is ready and I'll do the things.

2024-10-30 09:40 UTC, BlockBoi19 approved these changes
I've been looking for a indexedDB extension

2024-10-30 09:46 UTC, Drago-Cuven commented
miyo made a better one.

2024-10-30 09:52 UTC, BlockBoi19 commented
> miyo made a better one.

???

2024-11-07 22:12 UTC, Thebloxers998 commented
> miyo made a better one.

Link?

2024-12-24 23:14 UTC, yuri-kiss requested changes

2024-12-24 23:14 UTC, yuri-kiss commented on extensions/ffghdfh/indexedDB.js
> +(function (Scratch) {
Please add the header that other extensions have

2024-12-24 23:14 UTC, yuri-kiss commented on extensions/ffghdfh/indexedDB.js
> +      return new Promise((resolve, reject) => {
instead of re-initializing every time maybe only re-init if the DB-name was changed

2024-12-24 23:14 UTC, yuri-kiss commented on extensions/ffghdfh/indexedDB.js
> +      const { NAME } = args;
I'd recommend casting your key names for all the blocks.

2024-12-24 23:55 UTC, Thebloxers998 commented on extensions/ffghdfh/indexedDB.js
> +(function (Scratch) {
We really need this because it's important

2024-12-25 10:00 UTC, ffghdfh reviewed
Lol this all makes sense and stuff thanks guys lol
btw i'm not even sure this is the version i use since i've been using the one I sumbitted here https://github.com/ffghdfh/lemons-gallery-ff/blob/main/extensions/golbo/IndexedDB.js

2024-12-27 04:42 UTC, CubesterYT commented
!format

2024-12-27 04:53 UTC, GarboMuffin commented
!format

2024-12-27 04:54 UTC, CubesterYT commented
It worked!

2024-12-27 11:57 UTC, Thebloxers998 commented
> It worked!

Yep, it did

2025-01-12 01:28 UTC, GarboMuffin commented
I have been stalling on this because the dream is that users don't need to worry about where the data is stored; we transparently put it wherever it makes sense to.

2025-01-13 22:29 UTC, Thebloxers998 approved these changes, later dismissed

2026-02-15 22:15 UTC, Brackets-Coder commented
@ffghdfh is this still being worked on?

2026-02-22 17:58 UTC, ffghdfh commented
> @ffghdfh is this still being worked on?

Nnnnope not really, it works fine enough I guess? feel free to poke at it if you'd like

2026-02-22 17:59 UTC, ffghdfh commented
> > i've just been trying to add my extension and there was always something that came up! But i guess i just gotta play the waiting game...
> 
> Don't expect pull requests to be merged soon; GarboMuffin (TurboWarp's creator) has a job and mostly only is active here on weekends.

Mind you this was in 2024 and it still has not been merged yet

2026-02-22 18:14 UTC, Brackets-Coder commented
> Mind you this was in 2024 and it still has not been merged yet

Yes, I know this repository is notoriously slow. I'm doing my best to increase merge rates but to be honest we don't have the frameworks to keep the tap water flowing.

As garbomuffin mentioned, any kind of "storage" extension becomes complicated, so I'll see what I can do to review later (I'm busy right now). Hopefully we can get this merged soon but I really can't say for sure :/

2026-02-22 21:04 UTC, ffghdfh commented
That's alright, thank you for your help though :D

On Sun, 22 Feb 2026 at 19:14, Brackets-Coder ***@***.***>
wrote:

> *Brackets-Coder* left a comment (TurboWarp/extensions#1341)
> <https://github.com/TurboWarp/extensions/pull/1341#issuecomment-3941471458>
>
> Mind you this was in 2024 and it still has not been merged yet
>
> Yes, I know this repository is notoriously slow. I'm doing my best to
> increase merge rates but to be honest we don't have the frameworks to keep
> the tap water flowing.
>
> As garbomuffin mentioned, any kind of "storage" extension becomes
> complicated, so I'll see what I can do to review later (I'm busy right
> now). Hopefully we can get this merged soon but I really can't say for sure
> :/
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TurboWarp/extensions/pull/1341#issuecomment-3941471458>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AW7BSMRCVITIBP5452AB3MT4NHWZVAVCNFSM6AAAAACVG7CWUSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTSNBRGQ3TCNBVHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2026-07-04 13:47 UTC, Brackets-Coder commented
@ffghdfh 

One of the optimizations we've been trying to do is consolidating duplicate PRs (see #2271). Since #2087 has been closed, this is the main storage extension pull request open right now. 

As mentioned before, I think persistent browser storage is a great idea (e.g., for save codes) but this has to be a seamless experience and have a standardized storage location to be a great user experience for projects. Also, some users may want "Secure" storage (as seen various closed pull requests), and although this extension probably isn't intended to store sensitive information, some people might expect that and attempt to store sensitive information anyway.

> I have been stalling on this because the dream is that users don't need to worry about where the data is stored; we have one extension that transparently does the right thing.

@TurboWarp/extension-reviewers I may need some assistance evaluating the practicality of this extensions

Also, to get this merged, it would need to comply with the contributing guidelines. There's a few things we need to clean up before that can happen. Additionally, it would be nice if you could disclose the extent to which LLMs assisted the development of this extension (if at all)

2026-07-04 13:48 UTC, GarboMuffin commented
It would be better to teach the local storage extension to switch to better backends that allow more storage instead

2026-07-04 13:48 UTC, closed without merging

2026-07-04 13:50 UTC, Brackets-Coder commented
You mean like do a IndexedDB API backend for Local Storage?

2026-07-04 15:10 UTC, DNin01 commented
> It would be better to teach the local storage extension to switch to better backends that allow more storage instead

Like, with limits per project? Or a permission prompt for using more than a small amount of storage?