Tune Shark V3 Extension (Sound Extension with Audio Effects (poggers))
TurboWarp/extensions pull request #1489
Opened 2024-05-26 00:36 UTC by SharkPool-SP

2024-05-26 06:40 UTC, DDen4ik-12 commented
ERROR:
When I try to use the block ![Block](https://github.com/TurboWarp/extensions/assets/133135758/23163847-b03a-47d4-a86f-12f0d5499fdc), an error is displayed in the console:
![Errors](https://github.com/TurboWarp/extensions/assets/133135758/afea7a92-7e04-49b6-b7b9-0a44747457e5)

2024-05-26 16:31 UTC, SharkPool-SP commented
> ERROR:
> 
> When I try to use the block ![Block](https://github.com/TurboWarp/extensions/assets/133135758/23163847-b03a-47d4-a86f-12f0d5499fdc), an error is displayed in the console:
> 
> ![Errors](https://github.com/TurboWarp/extensions/assets/133135758/afea7a92-7e04-49b6-b7b9-0a44747457e5)
> 
> 

Weird. Scratch default sounds just do not like being added

2024-05-26 18:19 UTC, SharkPool-SP commented
@DDen4ik-12  Fixed. Its a problem with scratch, the only fix is to edit the scratch sound in some way before importing. Example: changing the pitch back and forth

2024-06-01 12:47 UTC, GaypataponALT commented
can you also add blocks that can detect the loudness of the sound? that would been great for music visualizers

2024-06-01 15:14 UTC, SharkPool-SP commented
> can you also add blocks that can detect the loudness of the sound? that would been great for music visualizers

already exists:
<img width="315" alt="Screenshot 2024-06-01 at 8 14 20 AM" src="https://github.com/TurboWarp/extensions/assets/139097378/cf375b4e-8d94-4eb7-92f3-3529a5e090a0">

2024-06-03 05:36 UTC, SharkPool-SP commented
Added 2 New Effects
![image](https://github.com/TurboWarp/extensions/assets/139097378/6c3c66c4-b271-48af-b691-0d31b3b8c96b)

2024-06-08 04:37 UTC, SharkPool-SP commented
![image](https://github.com/TurboWarp/extensions/assets/139097378/606f58c7-2c9d-4a7f-8f43-6e4977a98747)
New Audio Effect

2024-06-13 03:45 UTC, SharkPool-SP commented
new update:
![image](https://github.com/TurboWarp/extensions/assets/139097378/b62a234d-c8ef-4f1b-933c-cbdfa4de6889)

2024-07-18 03:30 UTC, SharkPool-SP commented
![image](https://github.com/user-attachments/assets/d37b63ed-2aea-4324-aefc-fd5e50dec4a1)
New Audio Effect

2024-07-24 03:05 UTC, SharkPool-SP commented
![image](https://github.com/user-attachments/assets/47e5e720-a915-4f28-a343-0e726b7c0860)

2025-01-04 00:53 UTC, SharkPool-SP commented
![image](https://github.com/user-attachments/assets/5a379132-a526-43ed-a78c-7771e1c0c3ac)
You can now read from specific channels!

2025-01-16 07:55 UTC, yuri-kiss commented
Can you fix linting please :sob:

2025-01-16 12:57 UTC, CubesterYT commented
!format

2025-01-18 00:16 UTC, CubesterYT commented
Ok first off, I'm going to fix some errors with the Validation, and add translation stuff.

2025-01-20 22:41 UTC, CubesterYT requested changes, later dismissed

2025-01-20 22:41 UTC, CubesterYT commented on extensions/SharkPool/Tune-Shark-V3.js
> +        Object.keys(soundBank).forEach((key) => {
Just make a constant of `Object.keys(soundBank)` before this if statement.

2025-01-20 22:41 UTC, CubesterYT commented on extensions/SharkPool/Tune-Shark-V3.js
> +      if (!Scratch.extensions.isPenguinMod) {
This is the TurboWarp repository, we rather you don't add checks for things like PenguinMod and whatnot or using PenguinMod APIs.

2025-01-20 22:41 UTC, CubesterYT commented on extensions/SharkPool/Tune-Shark-V3.js
> +      if (!Scratch.extensions.isPenguinMod) {
Same here.

2025-01-20 22:41 UTC, CubesterYT commented on extensions/SharkPool/Tune-Shark-V3.js
> +    // PenguinMod Storage
Same here as well, so you might as well make two copies of the extension.

2025-01-22 03:56 UTC, SharkPool-SP commented on extensions/SharkPool/Tune-Shark-V3.js
> +              "toggle sound link to [GO] [STOP] [ON_OFF]"
not adding due to documentation. Discussed in discord.

2025-01-22 03:57 UTC, SharkPool-SP commented on extensions/SharkPool/Tune-Shark-V3.js
> +            text: Scratch.translate("toggle sound [NAME] overlapping [TYPE]"),
not adding due to documentation. Discussed in discord.

2025-01-22 03:57 UTC, SharkPool-SP commented on extensions/SharkPool/Tune-Shark-V3.js
> +            text: Scratch.translate("toggle sound [NAME] reverse mode [TYPE]"),
not adding due to documentation. Discussed in discord.

2025-01-22 05:06 UTC, SharkPool-SP commented on extensions/SharkPool/Tune-Shark-V3.js
> +          Scratch.translate("Audio has not loaded yet, ignore next error.")
Update: No not fixable. Its a Pizzicato issue because the context is not initialized but playing requires it to have the source node.

The chance for this to actually error though is pretty low now throughout all the updates.

2025-01-22 05:06 UTC, SharkPool-SP commented
!format

2025-02-06 07:51 UTC, GarboMuffin requested changes, later dismissed
Not reviewed. I'm clicking this button so no one gets eager and merges it before the question of how to handle big external libraries without copying and pasting massive chunks of minified code

2025-03-18 11:35 UTC, CHCAT1320 commented
Wow, this is an awesome extension. Do you have a cover image for it so I can include it in my extension library website?

2025-03-18 16:29 UTC, SharkPool-SP commented
> Wow, this is an awesome extension. Do you have a cover image for it so I can include it in my extension library website?

Yeah it's one of the files where the code is

2025-03-19 11:06 UTC, CHCAT1320 commented
We hit some snags translating your extension to Simplified Chinese. For some unknown reason, when translating the menu, the blocks for changing the content don't work.

2025-05-04 22:07 UTC, SharkPool-SP commented
!format

2025-05-05 06:25 UTC, CHCAT1320 commented
Hi,I created an audio visualization using the new"data fft"feature,but it looks a bit strange.Could you take a look at the video below?
https://github.com/user-attachments/assets/52e743ba-1958-4f0f-832a-11b1ccf295cd

2025-06-13 20:25 UTC, SharkPool-SP commented
!format

2025-06-22 06:47 UTC, SharkPool-SP commented
!format

2026-01-17 08:04 UTC, SharkPool-SP commented
!format

2026-01-30 13:06 UTC, Brackets-Coder commented
Honestly I should probably review this too but I don't know when I'll find time since I'm busy this weekend
Probably a week or so? @SharkPool-SP Pester me about it until I review (just please don't make it unreasonable)

2026-01-30 16:31 UTC, SharkPool-SP commented
> Honestly I should probably review this too but I don't know when I'll find time since I'm busy this weekend
> 
> Probably a week or so? @SharkPool-SP Pester me about it until I review (just please don't make it unreasonable)

Okay

This extension is pretty much done now anyway

2026-02-08 00:41 UTC, SharkPool-SP commented
> Honestly I should probably review this too but I don't know when I'll find time since I'm busy this weekend Probably a week or so? @SharkPool-SP Pester me about it until I review (just please don't make it unreasonable)

pester

2026-02-08 03:25 UTC, Brackets-Coder commented
> > Honestly I should probably review this too but I don't know when I'll find time since I'm busy this weekend Probably a week or so? @SharkPool-SP Pester me about it until I review (just please don't make it unreasonable)
> 
> pester

okay, I'll try tomorrow but I don't know if I'll be able to do it

2026-02-14 18:25 UTC, Brackets-Coder reviewed
I haven't tested this and probably will later since I'm temporarily partially deaf in my left ear and can't hear very well at the moment

Skimming through the code. this looks alright. There's a few things I wanted to look at in the comments below. 

Apologies in advance if any of my questions are dumb, I'm very unfamiliar with this sound library

2026-02-14 18:25 UTC, Brackets-Coder commented on extensions/SharkPool/Tune-Shark-V3.js
> +              }
Haven't used this library before. Assuming this is used to keep sound consistent even at different delta times?

2026-02-14 18:25 UTC, Brackets-Coder commented on extensions/SharkPool/Tune-Shark-V3.js
> +              this.initSound(engine, args.NAME, url, false);
Shouldn't this be wrapped in Scratch.canFetch?

2026-02-14 18:25 UTC, Brackets-Coder commented on extensions/SharkPool/Tune-Shark-V3.js
> +            opcode: "setThingNew",
This is a very obscure opcode, try something like
```suggestion
            opcode: "newSetSoundEffect",
```

2026-02-14 18:25 UTC, Brackets-Coder commented on extensions/SharkPool/Tune-Shark-V3.js
> +          },
This block will definitely be used by many people. I'm just assuming you have to set the pan dynamically for 3D camera rotation/position

2026-02-14 18:25 UTC, Brackets-Coder commented on extensions/SharkPool/Tune-Shark-V3.js
> +            ),
Is this a lowpass filter like the one in https://scratch.mit.edu/projects/1227845221/

2026-02-14 18:25 UTC, Brackets-Coder commented on extensions/SharkPool/Tune-Shark-V3.js
> +              { text: Scratch.translate("length"), value: "length" },
Assuming this adjusts how slowly/quickly a sound plays. If so, does it also the pitch proportionally so you don't have squeaky voices when speeding up a recording? If so, is the scaling of pitch an optional user-exposed setting?

2026-02-14 18:25 UTC, Brackets-Coder commented on extensions/SharkPool/Tune-Shark-V3.js
> +      switch (type) {
any way this block can be cleaned up a bit? It seems like these properties are effect-exclusive, so I doubt it. If it can, great, if it can't, oh well it's not the end of the world

2026-02-14 18:25 UTC, Brackets-Coder commented on extensions/SharkPool/Tune-Shark-V3.js
> +          const newName = `${con.name}_COPY_${Math.random()}`;
If a user attempts to play dozens or hundreds of sounds simultaneously, will cloning this many contexts eat up browser resources?

2026-02-14 18:26 UTC, Brackets-Coder commented
Oops accidentally pressed enter before I was done reviewing...

2026-02-15 08:44 UTC, SharkPool-SP commented on extensions/SharkPool/Tune-Shark-V3.js
> +              }
web audio api (used by this library) does not have a built in 'speed' effect, so this mimics it.

answer to your question is yes

2026-02-15 08:47 UTC, SharkPool-SP commented on extensions/SharkPool/Tune-Shark-V3.js
> +              this.initSound(engine, args.NAME, url, false);
good catch

2026-02-15 08:59 UTC, SharkPool-SP commented on extensions/SharkPool/Tune-Shark-V3.js
> +            ),
not at all. That project is not lowpass at all (or not what it is known for)

Lowpass just makes it so lower frequencies can be played whereas higher frequencies are muted, and vise versa for highpass

2026-02-15 09:01 UTC, SharkPool-SP commented on extensions/SharkPool/Tune-Shark-V3.js
> +      switch (type) {
effect exclusive properties, no can do...

This is the cleanest it can be for efficiency (as far as I know) (seriously, check out what this looked like previously, was a fucking mess lmfao)

2026-02-15 09:01 UTC, SharkPool-SP commented on extensions/SharkPool/Tune-Shark-V3.js
> +              { text: Scratch.translate("length"), value: "length" },
length just returns the length of a song, so setters, only getter for this.

2026-02-15 09:03 UTC, SharkPool-SP commented on extensions/SharkPool/Tune-Shark-V3.js
> +          const newName = `${con.name}_COPY_${Math.random()}`;
might blast your ears off but no, `.clone()` reuses the audio buffer, so all audio overlays share the same audio 'context'

2026-02-16 00:21 UTC, Brackets-Coder commented on extensions/SharkPool/Tune-Shark-V3.js
> +      switch (type) {
Okay
But language

2026-02-16 00:54 UTC, SharkPool-SP commented on extensions/SharkPool/Tune-Shark-V3.js
> +      switch (type) {
:(

2026-02-25 20:19 UTC, Brackets-Coder submitted a review, later dismissed
making the pan really small values (e.g., position / 10) increases the loudness of the sound

pan should only affect stereo, not loudness?

It's probably because it thinks closer = louder and farther = quiet. It was working as expected for normal values, but the closer you get to 0 the weirder it gets. Maybe clamp it to a minimum of one? staying around 1-50 was fine

2026-02-26 06:55 UTC, SharkPool-SP commented
> making the pan really small values (e.g., position / 10) increases the loudness of the sound
> 
> pan should only affect stereo, not loudness?
> 
> It's probably because it thinks closer = louder and farther = quiet. It was working as expected for normal values, but the closer you get to 0 the weirder it gets. Maybe clamp it to a minimum of one? staying around 1-50 was fine

uhhhh doesnt sound like it to me?
Can u show a video or something

2026-05-15 17:13 UTC, SharkPool-SP commented
!format

2026-05-16 01:32 UTC, GarboMuffin commented
yolo merge?

2026-05-16 01:43 UTC, GarboMuffin commented on extensions/SharkPool/Tune-Shark-V3.js
> +          if (!canFetch) resolve();
you need to return at that point

2026-05-16 01:43 UTC, GarboMuffin commented on extensions/SharkPool/Tune-Shark-V3.js
> +      bufferSource.buffer = reverseBuffer(node.buffer);
this modifies the sound buffer in place, so if you import a Scratch sound and reverse it, everything using that buffer also gets reversed. so that would include the sound in regular Scratch and probably other imported copies of it

either:

 - copy buffer before changes
 - find a way to reverse it w/o changing the buffer

2026-05-16 01:44 UTC, GarboMuffin commented
Testing something. Might end up fixing and merging on my own.

2026-05-16 01:58 UTC, Brackets-Coder commented
> yolo merge?

Last time we tried that it broke production and we had to fix it with another PR but I'm down for a yolo merge any day

2026-05-16 02:37 UTC, GarboMuffin commented
you can see on the commits that claude credited itself this time

if you're happy with the changes i just made: send a picture of this message to me and i will merge it

2026-05-16 02:41 UTC, GarboMuffin approved these changes

2026-05-16 05:43 UTC, merged