Add GPU.sb3 extension
TurboWarp/extensions pull request #1762
Opened 2024-11-26 05:27 UTC by derpygamer2142

This adds blocks to use compute shaders in a Turbowarp project. This uses WebGPU(which is experimental!), and only supports compute shaders. From what little research I've done it seems like it would be a pain to add any of the other types, so I'm not doing that.

- Documentation [here](https://extensions.derpygamer2142.com/docs/gpusb3)
- Demos [here](https://extensions.derpygamer2142.com/demos)
- WGSL spec [here](https://www.w3.org/TR/WGSL/)
- WebGPU spec [here](https://www.w3.org/TR/webgpu/)
- WebGPU implementation status by browser [here](https://webgpu.io/)
- WebGPU fundamentals [here](https://webgpufundamentals.org/)

Notes:
- The only thing that's somewhat undocumented(I think, let me know if I forgot something) is buffer alignment and stuff, but webgpufundamentals does a better job of that.
- This doesn't work in the packager with electron. Not sure why, a quick google search leads me to [believe it's in beta](https://github.com/electron/electron/issues/26944).

![gpusb3](https://github.com/user-attachments/assets/2fc9812b-d8f3-4b7d-8a3c-f3c475f404a1)

2024-11-26 18:16 UTC, Thebloxers998 commented
It fails to get WebGPU adapter

2024-11-26 18:17 UTC, Thebloxers998 commented
What does the extension do

2024-11-26 21:12 UTC, derpygamer2142 commented
> It fails to get WebGPU adapter

what browser are you on, and what os

2024-11-26 21:13 UTC, derpygamer2142 commented
> What does the extension do

it's like pen+ but with numbers instead of colors and it all happens at the same time

2024-11-26 21:16 UTC, Thebloxers998 commented
> > It fails to get WebGPU adapter
> 
> what browser are you on, and what os

Chrome, Android, Why did you ask

2024-11-26 21:17 UTC, Thebloxers998 commented
> > What does the extension do
> 
> it's like pen+ but with numbers instead of colors and it all happens at the same time

That would be more hard but ok

2024-11-26 21:29 UTC, derpygamer2142 commented
> > > It fails to get WebGPU adapter
> > 
> > 
> > what browser are you on, and what os
> 
> Chrome, Android, Why did you ask?

WebGPU is experimental and doesn't work on some devices. Seems like android wouldn't be supported based on webgpu.io.

2024-11-26 22:25 UTC, Thebloxers998 commented
> > > > It fails to get WebGPU adapter
> > > 
> > > 
> > > what browser are you on, and what os
> > 
> > 
> > Chrome, Android, Why did you ask?
> 
> WebGPU is experimental and doesn't work on some devices. Seems like android wouldn't be supported based on webgpu.io.

Oh ok

2024-12-27 00:28 UTC, FurryR commented
well this is rough, make it more readable.

2024-12-27 02:43 UTC, LilyMakesThings commented on images/derpygamer2142/gpusb3.svg
no.

2024-12-27 02:44 UTC, LilyMakesThings commented on extensions/derpygamer2142/gpusb3.js
> +`); // GOD FUCKING DAMN IT "break if (condition)" IS IN THE OFFICIAL SPEC WHY THE HELL IS IT INVALID THIS IS BULLSHIT
Language.

2024-12-27 03:21 UTC, derpygamer2142 commented on images/derpygamer2142/gpusb3.svg
man

2024-12-27 03:22 UTC, derpygamer2142 commented
> well this is rough, make it more readable.

that's fair

2024-12-27 03:27 UTC, derpygamer2142 commented on images/derpygamer2142/gpusb3.svg
is it too silly or is it the intellectual property infringment

2024-12-27 03:52 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +`); // GOD FUCKING DAMN IT "break if (condition)" IS IN THE OFFICIAL SPEC WHY THE HELL IS IT INVALID THIS IS BULLSHIT
😔😔😔😔😔😔

2024-12-27 04:05 UTC, derpygamer2142 commented on images/derpygamer2142/gpusb3.svg
is the new thumbnail acceptable?

2024-12-27 23:41 UTC, FurryR commented
I'm excited to see the extension coming out as it means that we could now perform GPGPU calculations on TurboWarp, meaning that 3D applications will be blazingly fast and AI is now possible.

2024-12-28 23:11 UTC, derpygamer2142 commented
added a bunch of comments, removed profanity, and I think I reordered stuff in a way that makes more sense but I don't remember

2024-12-29 00:35 UTC, LilyMakesThings commented on images/derpygamer2142/gpusb3.svg
yes

2024-12-29 11:11 UTC, hablethedev commented on images/derpygamer2142/gpusb3.svg
yay my epic thumbnail :D

2025-01-22 15:22 UTC, derpygamer2142 commented
i have finally updated documentation to add the 3 new blocks

2025-01-31 14:59 UTC, derpygamer2142 commented
The latest commit(https://github.com/TurboWarp/extensions/pull/1762/commits/84c7b87ca44ab8815907336960d6518894e34ac2) adds error handling in case the device was lost or the project was run before it was finished getting the adapter+device. this makes pretty much every webgpu block async, which is pretty cringe. I could alternatively:
 - use .thens on the promise instead of awaiting it, removing the need for async(? not sure if this would work)
 - check if the device is invalid, and if it is just don't run the block while also throwing an error
 - do it anyways and add a way to check if the last block run threw an error

2025-02-08 01:13 UTC, derpygamer2142 commented
chose the last option as suggested
https://discord.com/channels/837024174865776680/1132437506655268926/1337565380243099679

2025-02-28 18:43 UTC, derpygamer2142 commented
i need to make some changes to the gpu.sb3 compiler so it doesn't get broken by translations

2025-04-05 20:38 UTC, derpygamer2142 commented
changes complete, this is ready for review

2025-04-08 02:56 UTC, yuri-kiss requested changes
yeah this is going to be a multipart review if i get around to it, this is giant and out of the scope of my knowledge as I dont know webgpu

2025-04-08 02:56 UTC, yuri-kiss commented on extensions/derpygamer2142/gpusb3.js
> +// ID: gpusb3
this id should contain a form of your name

2025-04-08 02:56 UTC, yuri-kiss commented on extensions/derpygamer2142/gpusb3.js
> +  Scratch.vm.runtime.on("EXTENSION_ADDED", () => {
maybe use runtime.off when you finally get the right extension

2025-04-08 02:56 UTC, yuri-kiss commented on extensions/derpygamer2142/gpusb3.js
> +  };
these should probably be constants

2025-04-08 02:56 UTC, yuri-kiss commented on extensions/derpygamer2142/gpusb3.js
> +        );
you should find a better way to tell the user that webGPU isnt available

2025-04-08 02:56 UTC, yuri-kiss commented on extensions/derpygamer2142/gpusb3.js
> +      };
just add these props on the error object instead of reassigning it, its clearer if you do

2025-04-08 02:56 UTC, yuri-kiss commented on extensions/derpygamer2142/gpusb3.js
> +      }
these functions dont differ, there is no need to use util here

2025-04-08 02:56 UTC, yuri-kiss commented on extensions/derpygamer2142/gpusb3.js
> +        docsURI: "https://extensions.derpygamer2142.com/docs/gpusb3",
make this the would be tw docs page instead please

2025-04-08 13:02 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +  };
it makes it easier to reset and is used to reduce duplicate code in the bind group entry block:
```js
    bindGroupEntry(args, util) {
      ...
      const kv = {
        buffer: "buffers",
        storageTexture: "textures",
        sampler: "samplers",
      }; // bind group entry type -> resources key

      // the object to bind to that slot. buffers are freaky and need a special object
      let o;
      const type = kv[args.TYPE] ?? "buffers";
      if (
        !Object.prototype.hasOwnProperty.call(
          resources[type],
          Scratch.Cast.toString(args.RESOURCE)
        )
      ) {
        return this.throwError(
          "ResourceNotFound",
          "The specified resource doesn't exist",
          "BindGroupEntryBlock",
          `Either the resource type is invalid or the provided resource name doesn't exist.`,
          util
        );
      }
      if (type == "buffers") {
        o = {
          buffer: buffers[args.RESOURCE],
        };
        //console.log(o)
      } else {
        o = resources[type][args.RESOURCE];
        if (type == "textures") o = o.createView();
      }
      
      ...
      }

```

2025-04-08 13:05 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +        );
this was requested by a couple people as opposed to showing an alert and not working anymore so the project can gracefully fall back on something else

2025-04-08 13:11 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +      };
like
```js
throwError(name, body, source, full, util) {
      name = name ?? "Undefined. This is an error, please report it!";
      body = body ?? "Undefined. This is an error, please report it!";
      source = source ?? "Undefined. This is an error, please report it!";
      full = full ?? "Undefined. This is an error, please report it!";
      
      error = { name, body, source, full };
      
      ...
}
```

2025-04-08 13:14 UTC, yuri-kiss commented on extensions/derpygamer2142/gpusb3.js
> +      };
no?

2025-04-08 13:14 UTC, yuri-kiss commented on extensions/derpygamer2142/gpusb3.js
> +        );
you should still alert the user if the project isnt packaged

2025-04-08 13:15 UTC, yuri-kiss commented on extensions/derpygamer2142/gpusb3.js
> +  };
its less clear and can be prone to bugs

2025-04-08 13:51 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +      };
k then i'm not really sure what you mean

2025-05-18 05:15 UTC, derpygamer2142 commented
i'm planning on adding some utilities for struct building on the cpu and maybe possible perhaps some rendering stuff, let me know if you have any ideas as to what this should look like

2025-05-27 20:22 UTC, derpygamer2142 commented
vadik came in clutch and told me that I can just put the texture of a skin to a canvas that was rendered to via webgpu, I'm going to add that

2025-09-16 22:17 UTC, Brackets-Coder commented
Is this still a thing or is it stagnant?

2025-09-17 02:27 UTC, derpygamer2142 commented
> Is this still a thing or is it stagnant?

it is, i'm just waiting for this pr to be reviewed and i'm working on adding rendering

2025-09-17 11:53 UTC, Brackets-Coder commented
> > Is this still a thing or is it stagnant?
> 
> it is, i'm just waiting for this pr to be reviewed and i'm working on adding rendering

Okay this one is bigger so I'll review it when I have time

2025-09-17 12:57 UTC, derpygamer2142 commented
> > > Is this still a thing or is it stagnant?
> > 
> > 
> > it is, i'm just waiting for this pr to be reviewed and i'm working on adding rendering
> 
> Okay this one is bigger so I'll review it when I have time

thats what they all said

2025-09-17 12:59 UTC, Brackets-Coder commented
> > > > Is this still a thing or is it stagnant?
> > > 
> > > 
> > > it is, i'm just waiting for this pr to be reviewed and i'm working on adding rendering
> > 
> > 
> > Okay this one is bigger so I'll review it when I have time
> 
> thats what they all said

Okay, I'll tell you what. I'll get around to it at my earliest convenience, likely sometime today

2025-09-17 13:45 UTC, CubesterYT commented
I'll look over it too

2025-09-17 13:51 UTC, Brackets-Coder reviewed
This extension is so large and beyond my pay grade I don't think I'll be of much help
As I've said in one of these comments, I'm more familiar with rendering libraries than the lowest-level of the APIs...

Unfortunately I haven't made time to test this yet but it seems like this one will be quite an endeavor.

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +// License: MIT
Are you using MIT out of personal preference or because you're using a library that uses it?

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +    bufferRefs = {}, // deprecated, not used anywhere anymore
If it's deprecated why didn't you remove it

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +    samplers = {}; // this doesn't work with compute shaders but i kept it in case i lock in and add other stuff(extremely unlikely but deleting code causes me pain)
Okay, these seem unfinished but since it causes you emotional damage I suppose you can leave them

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +      }
Nice check, does the website educate users on whether their browser has experimental support as feature flags? A lot of people say Safari doesn't support WebGPU but I'm extremely familiar with macOS and it's actually hidden behind a "Stable" feature flag after enabling developer settings...

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +    }
This is your reminder to uncomment

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +    }
Unless I'm wrong can you make them part of an object and do something like this

```suggestion
    resourceFromType(type) {
        return resources[type];
    }
```
If it's not possible that's okay but it might help clean it up a lot since all of the strings are exactly the same as the name of the returned values.

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +        // color3: "#032966",
Were these important?

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +              // and thought that was a good idea despite it being horrible and the least efficient way to do it
Clarify what you mean?

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +                // GPUFUNC is an old name that i am to scared to change
if GPUFUNC is a bad name it doesn't hurt to change

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +                defaultValue: Scratch.translate("myBindGroup"),
@CubesterYT Were we supposed to be translating the default values because I never have

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +            hideFromPalette: true,
Why is this block hidden?

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +            // you can write data from the cpu to the gpu which is pretty cool
Nice

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +            hideFromPalette: true,
You might want to check that...

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +            // this continues to exist in case i add other shader types, which is extremely unlikely
Huh

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +            // https://webidl.spec.whatwg.org/#AllowSharedBufferSource
why not remove it

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +          // for the love of whatever deity you may or may not believe in, do not use mdn as a reference for webgpu. it has incorrect and outdated information
Um
Noted about MDN
I'm going to have to educate myself because while I know the _very_ basics of graphics stuff, I normally don't work with the low-level APIs directly and do more stuff with WebGPU in Three.js...

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +                defaultValue: "vec3",
I think this is the only defaultValue I've come across so far that isn't translated... was this intentional?

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +            hideFromPalette: true, // this doesn't work with compute shaders, but if i decide to get freaky and somehow add other shader types(i probably won't) why redo code
Okay

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +                defaultValue: JSON.stringify([1]),
why can't you just... 
```suggestion
                defaultValue: "1",
```

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +          },
so I take it C blocks have to be described as conditionals with a branchCount?

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +            },
Why was one of the arguments commented out, that's pretty crucial

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +          {
Since this extension has so many blocks, have you thought about separating the categories with the spacers? like this


```suggestion
          },
          "---"
          {
            blockType: "label",
            text: Scratch.translate("thread safety"),
          },

          {
```

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +          // webgpu/wgsl stuff intentionally not translated
Noted, but why was it intentional?

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +          },
I know what a majority of these do
but you could potentially remove the random offhand comments to the people reading the file, it just adds extra lines

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +              // "textureSampleCompareLevel"
Sad there's only compute shaders, fragment would be so helpful

So aka this does things with compute like this: 
https://threejs.org/examples/?q=webgpu#webgpu_compute_birds
https://threejs.org/examples/?q=webgpu#webgpu_compute_particles_fluid

but no fragment/vertex shaders like you would normally see in rendering processes?

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +              "Float64Array",
You may want to put this in the documentation if it isn't already there,
**Also I don't see any markdown file for documentation in this PR, even though you put a docsURL in getInfo()...**

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +      // and it's a whole thing.
Be careful with accept reporters in your menus and make sure you're casting

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +        }
for all of these couldn't you just consolidate them into something like
```
return blob.fields[toUpperCase(blob.opcode.replace("gpusb3_menu_", ""))].value;
```

I might be misunderstanding but it's just an idea

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +        }
Um
This looks important

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +            let op = "How do you mess up this badly?"; // this shouldn't ever be present unless you intentionally do it
wait what is this exactly

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +            code = code.concat(this.genWGSL(util, b.NAME, recursionDepth + 1)); // if your variable name is invalid it's your own fault and you can cry about it
What makes an invalid variable name, you should also put that in the documentation

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +              // barrier block minecraft??????
I'm quite sure this comment is unnecessary

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +        // if (!Object.prototype.hasOwnProperty.call(parsed,"type")) throw new Error("skibidi toilet ohio grimace shake rizz")
We gonna fix the brainrot error?

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +      // and send it back to the gpu
That sounds... complicated and unperformant, again, probably should be in the documentation

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +    }
Do these blocks actually do anything other than return what they're supposed to do

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +        if (!Array.isArray(j)) throw new Error("skibidi toilet ohio rizz");
I don't think this is an acceptable error to throw.

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +        console.log("aaaaa");
ummm why

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +          throw new Error("balkan rage winter arc jonkler trollge phonk"); // 🤫🧏
Preferably, if you're going to throw an error make it clear, purposeful, and helpful, not as a joke

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +    }
Do these blocks actually do anything?

2025-09-17 13:51 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +    }
Do these blocks actually do anything?

2025-09-17 13:51 UTC, Brackets-Coder commented on images/derpygamer2142/gpusb3.png
That looks an awful lot like an Nvidia GPU, and you can't really have text in your banner due to translation and typography...

2025-09-17 13:51 UTC, Brackets-Coder commented on package-lock.json
> +        "@webgpu/types": "^0.1.51",
is webgpu types absolutely required for this extension

2025-09-17 13:55 UTC, Brackets-Coder commented
I'd recommend putting your documentation at extensions.turbowarp.com, just because some users may not trust your personal site.

Also, considering how much this extension appears to be a work-in-progress, I'm going to convert it to a draft, **but if I'm wrong please feel free to open it up again.**

2025-09-17 14:21 UTC, CubesterYT commented on extensions/derpygamer2142/gpusb3.js
> +                defaultValue: Scratch.translate("myBindGroup"),
Usually yeah

In some cases, no

2025-09-17 17:49 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +    }
yes, they are used in the compiler and if the functions were not present it would throw errors.

2025-09-17 17:50 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +// License: MIT
The penguinmod gallery requires all extensions to be licensed under MIT

2025-09-17 17:52 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +    samplers = {}; // this doesn't work with compute shaders but i kept it in case i lock in and add other stuff(extremely unlikely but deleting code causes me pain)
it's planned now anyways

2025-09-17 17:53 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +      }
yes

2025-09-17 17:53 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +    }
it's already uncommented so it's fine

2025-09-17 17:55 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +// License: MIT
Okay, since we don't have strict requirements I suppose this is acceptable.

2025-09-17 17:56 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +                // GPUFUNC is an old name that i am to scared to change
i can update that comment, it's for penguinmod compatibility

2025-09-17 18:52 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +            hideFromPalette: true,
samplers are not available in compute shaders

2025-09-17 21:47 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +                defaultValue: "vec3",
yes, those are the direct wgsl types and i left them like that so that it's easier for people who learn how to use this extension to use the actual webgpu api. there are more further down

2025-09-17 21:48 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +                defaultValue: JSON.stringify([1]),
"[1]", just as a sanity check

2025-09-17 21:50 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +            },
i did that to keep people from typing in the argument slot, i could probably change that but i'm still not sure how much to "childproof" this extension.

2025-09-17 21:53 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +          // webgpu/wgsl stuff intentionally not translated
@CubesterYT said not to, https://discord.com/channels/837024174865776680/1132437506655268926/1345066146625491095 if you're in the turbowarp discord

2025-09-17 21:54 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +              // "textureSampleCompareLevel"
no, that is planned though

2025-09-17 21:55 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +              "Float64Array",
that was already requested by a now former reviewer and i was planning on doing it after all the documentation was done

2025-09-17 21:57 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +      // and it's a whole thing.
pretty sure i already cast what's needed, and accepting reporters is another part of the question about child proofing

2025-09-17 21:59 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +        }
some of them do not follow that rule, such as with blocks that have no arguments which are not used yet, but are part of the unused sampler code

2025-09-17 22:01 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +            let op = "How do you mess up this badly?"; // this shouldn't ever be present unless you intentionally do it
maps the operator_mathop block to various math operations, the comment is for reference of the difference options

2025-09-17 22:04 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +            code = code.concat(this.genWGSL(util, b.NAME, recursionDepth + 1)); // if your variable name is invalid it's your own fault and you can cry about it
anything besides a-Z, numbers and underscores or having the variable name start with a number

2025-09-17 22:06 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +    }
reporters return a short blurb of documentation for some usability and the functions existing prevents errors

2025-09-17 22:06 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +        if (!Array.isArray(j)) throw new Error("skibidi toilet ohio rizz");
oh this is the only one that's here unintentionally i will fix that

2025-09-17 22:09 UTC, derpygamer2142 commented on images/derpygamer2142/gpusb3.png
it is a brandless and definitely not traced gpu and i think the .sb3 is fine because it's a file extension, but i'll ask if the "by" part can be removed

2025-09-17 22:10 UTC, derpygamer2142 commented on package-lock.json
> +        "@webgpu/types": "^0.1.51",
it is borderline impossible to develop this extension without it but it is not required for the functionality

2025-09-18 07:44 UTC, hablethedev commented on images/derpygamer2142/gpusb3.png
Heya, just made [PR 2](https://github.com/derpygamer2142/example-extensions-fork/pull/2) which just updates the image a little bit. I'm not the best at Git but if it gets accepted this PR updates, right...?

2025-09-20 01:54 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +            // https://webidl.spec.whatwg.org/#AllowSharedBufferSource
there's a nonzero chance that someone from a specific group will complain and i'd rather have this be here now than need to add it back when they have problems. i'll remove the unused variables though and just make this a noop if that works

2025-09-20 01:58 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +    }
that was how it was originally but a reviewer asked for it to be changed

2025-09-20 02:00 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +        // color3: "#032966",
no, i originally got rid of it so the colors were exactly the same in the docs as the actual extension. i'll remove those comments

2025-09-20 02:04 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +              // and thought that was a good idea despite it being horrible and the least efficient way to do it
idk how this vscode review extension works or if it waits to post my response until after i've commited but i am making a change here

2025-09-20 02:19 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +        }
i remembered what i was writing there, fixed

2025-09-20 02:23 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +        console.log("aaaaa");
whoops old sanity check from when i was trying to figure out where hard to track down errors were happening, removed

2025-09-20 02:24 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +          throw new Error("balkan rage winter arc jonkler trollge phonk"); // 🤫🧏
fixed

2025-09-20 02:24 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +    bufferRefs = {}, // deprecated, not used anywhere anymore
done

2025-09-20 02:31 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +            hideFromPalette: true,
it seems fine, i'll unhide it. also changing the default value

2025-09-20 17:47 UTC, derpygamer2142 commented on images/derpygamer2142/gpusb3.png
fixed

2025-09-20 18:16 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +        }
Yes but you could only do that for the ones that do follow the rule (e.g, only the ones that start with gpusb3_menu_

2025-09-20 20:08 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +          },
done

2025-09-20 20:08 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +          {
done

2025-09-20 20:24 UTC, Brackets-Coder commented on extensions/derpygamer2142/gpusb3.js
> +    }
IMO it just looks messier

2025-09-20 20:35 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +        }
done

2025-09-20 20:35 UTC, derpygamer2142 commented on extensions/derpygamer2142/gpusb3.js
> +        if (!Array.isArray(j)) throw new Error("skibidi toilet ohio rizz");
fixed

2026-06-16 06:44 UTC, derpygamer2142 commented
i don't plan on finishing this and i don't plan on being a part of anything scratch related anymore. as it stands this extension should not be used for any form of rendering(it will be unbelievably slow in at least 3 ways), you're better off using pen+ for that. this will work for compute shaders though. also it might break due to changes to the spec, but i've heard it's relatively stable so who knows. thank you for being willing to review this, even if roughly.

2026-06-16 06:44 UTC, closed without merging

2026-06-16 11:07 UTC, Brackets-Coder commented
That's a shame, I was looking forward to GPU particle simulations in TW, but totally understand