LoginNexus
TurboWarp/extensions pull request #1813
Opened 2024-12-25 13:42 UTC by Thebloxers998

A REST API-based authentication and registration extension 

Unlock the **REST API-BASED** authentication/registration for games

Any ideas or feedback? Tell me 💡

2024-12-25 13:44 UTC, Thebloxers998 commented
(Sorry for reuploading a extension,  its due to the conflicts)

2024-12-25 13:48 UTC, yuri-kiss requested changes
API keys are a touchy area as they are unsafe and can be easily stolen.
Please see AI extensions for reference as they require an API key and have been touched on a lot for this matter.

2024-12-25 13:48 UTC, yuri-kiss commented on extensions/login-nexus.js
> +            this.clientId = args.CLIENT_ID;
You need to cast your arguments on all your blocks

2024-12-25 13:48 UTC, yuri-kiss commented on extensions/login-nexus.js
> +        const response = await Scratch.fetch(this.apiUrl , {
you need to check Scratch.canFetch

2024-12-25 13:48 UTC, yuri-kiss commented on extensions/login-nexus.js
> +        const response = await Scratch.fetch(this.apiUrl);
check here too

2024-12-25 13:48 UTC, yuri-kiss commented on extensions/login-nexus.js
> +                    Scratch.openWindow(`https://accounts.google.com/o/oauth2/auth?client_id=${this.clientId}&redirect_uri=${this.redirectUri}&response_type=token&scope=email`, '_blank');
check if you are allowed to do this before you do, see network for reference

2024-12-25 13:48 UTC, yuri-kiss commented on extensions/login-nexus.js
> +                id: 'loginNexus',
this id needs to container a form of your username

2024-12-25 13:48 UTC, yuri-kiss commented on extensions/login-nexus.js
please put this in a user folder if possible

2024-12-25 14:05 UTC, Thebloxers998 commented
> API keys are a touchy area as they are unsafe and can be easily stolen. Please see AI extensions for reference as they require an API key and have been touched on a lot for this matter.

Api keys?

2024-12-25 14:05 UTC, Thebloxers998 commented
> > API keys are a touchy area as they are unsafe and can be easily stolen. Please see AI extensions for reference as they require an API key and have been touched on a lot for this matter.
> 
> Api keys?

Oh, I checked the code, I did a spelling mistake

2024-12-26 10:11 UTC, Thebloxers998 commented
!format

2024-12-27 04:57 UTC, GarboMuffin commented
!format

2025-01-03 17:45 UTC, Thebloxers998 commented
I dont wanna add this anymore

2025-01-03 17:45 UTC, closed without merging