ShovelUtilsTW
TurboWarp/extensions pull request #189
Opened 2023-02-12 12:55 UTC by TheShovel

TurboWarp version of my misc utilities extension.

It includes:

-Blocks for importing/loading stuff from links
![image](https://user-images.githubusercontent.com/68913917/218312150-a638d852-7112-4ba5-bd86-4ab7615a2475.png)

-Blocks for setting lists to a json array, and getting their data
![image](https://user-images.githubusercontent.com/68913917/218312204-120525f9-1235-4831-a905-510bde8e838f.png)

-And other misc blocks
![image](https://user-images.githubusercontent.com/68913917/218312281-fba75fc2-907e-499f-aa9d-75b4aee9c817.png)

2023-02-12 12:58 UTC, TheShovel commented
Well that's weird. Why is it saying that stuff is not defined when I did define them?

2023-02-12 14:06 UTC, softedco commented
> Well that's weird. Why is it saying that stuff is not defined when I did define them?

You can't define stuff as null because null is basically the same thing as undefined.

2023-02-12 14:43 UTC, softedco requested changes
this should probably do

2023-02-12 14:43 UTC, softedco commented on extensions/TheShovel/ShovelUtilsTW.js
> +tempImageLoad = null
```suggestion
var tempImageLoad = {};
```
fixes tempImageLoad is not defined
also it appears to be completely unused

2023-02-12 14:43 UTC, softedco commented on extensions/TheShovel/ShovelUtilsTW.js
> +string = null;
```suggestion
var string = '';
```
fixes string is not defined
also unused

2023-02-12 14:43 UTC, softedco commented on extensions/TheShovel/ShovelUtilsTW.js
> +temp = null;
```suggestion
var temp = {};
```
fixes temp is not defined

2023-02-12 14:43 UTC, softedco commented on extensions/TheShovel/ShovelUtilsTW.js
> +tempVAR = null;
```suggestion
var tempVAR = {};
```
fixes tempVAR is not defined
also unused

2023-02-12 14:43 UTC, softedco commented on extensions/TheShovel/ShovelUtilsTW.js
> +(function(Scratch) {
```suggestion
(function(Scratch) {
  'use strict';
```
fixes use the function form of use strict

2023-02-12 14:43 UTC, softedco commented on extensions/TheShovel/ShovelUtilsTW.js
> +  'use strict';
```suggestion

```
I guess it shouldn't be there

2023-02-12 14:43 UTC, softedco commented on extensions/TheShovel/ShovelUtilsTW.js
> +    var m = color.match(/(\d+){3}/g);
```suggestion
    m = color.match(/(\d+){3}/g);
```
fixes m is already defined

2023-02-12 14:43 UTC, softedco commented on extensions/TheShovel/ShovelUtilsTW.js
> +    if (m) var r = m[0], g = m[1], b = m[2];
```suggestion
    if (m) r = m[0], g = m[1], b = m[2];
```
fixes r is already defined

2023-02-12 14:43 UTC, softedco commented on extensions/TheShovel/ShovelUtilsTW.js
> +  var color = "" + color, isHEX = color.indexOf("#") == 0, isRGB = color.indexOf("rgb") == 0;
```suggestion
  color = "" + color;
  var isHEX = color.indexOf("#") == 0, isRGB = color.indexOf("rgb") == 0;
```
fixes color is already defined

2023-02-12 15:48 UTC, Mickmick2012 commented
looks good ! I was hopping to see this

2023-02-12 18:53 UTC, TheShovel commented
Thanks a lot for fixing the issue @softedco :D

2023-02-12 20:49 UTC, GarboMuffin commented on extensions/TheShovel/ShovelUtilsTW.js
> +var tempImageLoad = {};
All of these variables need to go underneath `(function(Scratch) {` below so they don't pollute the global scope

2023-02-12 21:07 UTC, TheShovel commented
Oh god I just realized what those buttons do. I am sorry lmao.

2023-02-13 00:36 UTC, GarboMuffin commented on extensions/TheShovel/ShovelUtilsTW.js
> +  vm.extensionManager.loadExtensionURL(TEXT)
wrap this in `if (await vm.securityManager.canLoadExtensionFromProject(url)) {`

2023-02-15 17:06 UTC, TheShovel commented
![shovelutils](https://user-images.githubusercontent.com/68913917/219101029-c5347cfd-ecf0-4b84-9093-5309a28ce51b.png)

Image

2023-02-16 18:47 UTC, merged