Add SuperAlert
TurboWarp/extensions pull request #735
Opened 2023-07-13 04:05 UTC by 0832k12

An extension can open an Alert at the center of screen.
![image](https://github.com/TurboWarp/extensions/assets/70421730/227561a0-5fa9-4160-8a64-94ae3805a0c4)

2023-07-13 11:06 UTC, Martinelplayz commented
can you make options for the user to press? like (yes, no) (accept, cancel) etc

2023-07-13 21:17 UTC, horizontal-shading commented
Why are the blocks in chinese?

2023-07-13 21:20 UTC, CST1229 commented
> Why are the blocks in chinese?

Probably because the creator is Chinese.

2023-07-20 18:30 UTC, SharkPool-SP commented
Can you add more blocks that can customize the alert box? Here is some concept blocks I made (that do work, so this is possible): 
<img width="578" alt="Screen Shot 2023-07-20 at 11 11 52 AM" src="https://github.com/TurboWarp/extensions/assets/139097378/c750b064-048b-41ff-807f-809bd17aa504">
Heres the .js file with the blocks. If you use this, you don't have to give me credit: 
[New Alert Blocks.js.zip](https://github.com/TurboWarp/extensions/files/12113006/New.Alert.Blocks.js.zip)

2023-07-21 02:09 UTC, 0832k12 commented
That 's a good advice.

2023-07-21 02:22 UTC, 0832k12 commented
![image](https://github.com/TurboWarp/extensions/assets/70421730/65b48190-ddd0-4fb3-87ba-798f3de467ee)
![image](https://github.com/TurboWarp/extensions/assets/70421730/73c1b72e-2c56-4dd9-968f-7fc4f00740a6)

2023-07-21 03:48 UTC, SharkPool-SP commented
> ![image](https://user-images.githubusercontent.com/70421730/255055375-65b48190-ddd0-4fb3-87ba-798f3de467ee.png) ![image](https://user-images.githubusercontent.com/70421730/255055391-73c1b72e-2c56-4dd9-968f-7fc4f00740a6.png)

SICK!!!! How did you get the select color block argument?

2023-07-22 18:17 UTC, SurvExe1Pc commented
> > ![image](https://user-images.githubusercontent.com/70421730/255055375-65b48190-ddd0-4fb3-87ba-798f3de467ee.png) ![image](https://user-images.githubusercontent.com/70421730/255055391-73c1b72e-2c56-4dd9-968f-7fc4f00740a6.png)
> 
> SICK!!!! How did you get the select color block argument?

`Scratch.ArgumentType.COLOR`

2023-07-22 18:30 UTC, SharkPool-SP commented
> > > ![image](https://user-images.githubusercontent.com/70421730/255055375-65b48190-ddd0-4fb3-87ba-798f3de467ee.png) ![image](https://user-images.githubusercontent.com/70421730/255055391-73c1b72e-2c56-4dd9-968f-7fc4f00740a6.png)
> > 
> > 
> > SICK!!!! How did you get the select color block argument?
> 
> `Scratch.ArgumentType.COLOR`

Oh ok, thanks!

2023-08-22 21:56 UTC, NexusKitten requested changes
Also change the JS and extensions.json to comply with the new policies in [CONTRIBUTING.md](https://github.com/TurboWarp/extensions/blob/master/CONTRIBUTING.md).
Looking forward to this extension.

2023-08-22 21:56 UTC, NexusKitten commented on extensions/0832/SuperAlert.js
> +                    textOptions: [
Any reason this isn't acceptreporters: true?

2023-08-22 21:56 UTC, NexusKitten commented on extensions/0832/SuperAlert.js
> +                    alignmentOptions: [
Any reason this isn't acceptreporters: true?

2023-08-22 21:56 UTC, NexusKitten commented on extensions/0832/SuperAlert.js
> +                id: 'tc',
Extension ID should generally be more descriptive, containing the username of the person who made it and the extension's name. "k12superalert" would be a better ID, for example.

2023-08-22 21:56 UTC, NexusKitten commented on extensions/0832/SuperAlert.js
> +                name: Scratch.translate({ id: 'name', default: 'Alert' }),
Probably a translation error, but you may want to rename the extension default to 'SuperAlert' to align with the name in the Pull Request.

2023-08-22 21:56 UTC, NexusKitten commented on extensions/0832/SuperAlert.js
> +        d() {
It appears there's no way to open a text box with it's contents already defined; it'll always be empty for a few frames before content is added. Is there a way around this?

2023-08-22 21:56 UTC, NexusKitten commented on extensions/0832/SuperAlert.js
> +                    fontOptions: [
Be careful with font options, as not all built-in fonts are supported on every device. Preferably, the extension could run off of fonts from the VM, but I'm not sure if that's possible, so the current solution is alright.

2023-08-27 00:59 UTC, SharkPool-SP commented
> can you make options for the user to press? like (yes, no) (accept, cancel) etc

I did this in Better Input

2023-08-27 01:04 UTC, LilyMakesThings commented
> > can you make options for the user to press? like (yes, no) (accept, cancel) etc
> 
> I did this in Better Input

sir this is the pr for superalert
![image](https://github.com/TurboWarp/extensions/assets/127533508/3e8688ed-0d45-414a-9efa-8748598f9806)

2023-08-27 06:15 UTC, SharkPool-SP commented
> > > can you make options for the user to press? like (yes, no) (accept, cancel) etc
> > 
> > 
> > I did this in Better Input
> 
> sir this is the pr for superalert ![image](https://user-images.githubusercontent.com/127533508/263503016-3e8688ed-0d45-414a-9efa-8748598f9806.png)

ma'am, we are both using CSS. I have no argument but still. Work is already done lmao

2023-08-27 16:35 UTC, Cbr2011 commented
i like to see this extension be merged.
i also like if every time the user clicks out of the popup or ESC is pressed, The popup closes

2023-08-27 17:48 UTC, SharkPool-SP commented
> i like to see this extension be merged.
> i also like if every time the user clicks out of the popup or ESC is pressed, The popup closes

Just use an if statement and close the box if true

2023-08-27 18:09 UTC, Cbr2011 commented
> > i like to see this extension be merged.
> > i also like if every time the user clicks out of the popup or ESC is pressed, The popup closes
> 
> Just use an if statement and close the box if true

oh ok

2023-11-01 21:00 UTC, SurvExe1Pc commented
guys we love XSS

2023-11-01 21:13 UTC, SurvExe1Pc commented
i mean this pull seems dead but this extension has XSS in it.
![image](https://github.com/TurboWarp/extensions/assets/135030944/3c7df2be-8b8c-4e22-82e4-29c8105d1528)

2023-11-01 23:56 UTC, CubesterYT commented
W xss /j

2023-11-02 03:39 UTC, closed without merging

2023-11-02 11:09 UTC, CubesterYT commented
Why was this closed?