Add TOTP code and AES encryption extension.
TurboWarp/extensions pull request #939
Opened 2023-08-24 08:33 UTC by LIZARD-OFFICIAL

Restored AES.js
Just made a two-factor authentication extension.
You can literally make a 2FA app in scratch now
@GarboMuffin Please merge

2023-08-24 08:41 UTC, NexusKitten commented
It would help if you could separate these two extensions into separate pull requests, so we can review them individually.

2023-08-24 08:53 UTC, LIZARD-OFFICIAL commented
> It would help if you could separate these two extensions into separate pull requests, so we can review them individually.

I can't create two forks of same repo

2023-08-24 09:17 UTC, NexusKitten commented
> > It would help if you could separate these two extensions into separate pull requests, so we can review them individually.
> 
> I can't create two forks of same repo

Use [branches.](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository)

2023-08-24 09:32 UTC, CST1229 commented
> > > It would help if you could separate these two extensions into separate pull requests, so we can review them individually.
> > 
> > 
> > I can't create two forks of same repo
> 
> Use [branches.](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository)

Also, don't use the `master` branch.

2023-08-25 13:25 UTC, LIZARD-OFFICIAL commented
@GarboMuffin Please add it this time.

2023-08-25 15:30 UTC, NexusKitten requested changes
Some other finishing comments:
- Both extensions need to start with the metadata the other extensions do- see [CONTRIBUTING.md](https://github.com/TurboWarp/extensions/blob/master/CONTRIBUTING.md).
- Consider documentation for one or both of these extensions, as both of thier purposes are rather complex and may be confusing to other audiences.

2023-08-25 15:30 UTC, NexusKitten commented on extensions/LIZARD_OFFICIAL/2FA.js
> +/* eslint-disable */
Using `/* eslint-disable */` for the whole script is generally not a good idea, it's required for the library you imported but you should add an `/* eslint-enable */` afterwards.

2023-08-25 15:30 UTC, NexusKitten commented on extensions/LIZARD_OFFICIAL/2FA.js
> +        id: "twofactorauth",
The extension ID should contain someway to identify it's made by you. Something like "lizard2fauth" would work.

2023-08-25 15:30 UTC, NexusKitten commented on extensions/LIZARD_OFFICIAL/2FA.js
> +      return new jsOTP.totp().getOtp(args.CODE).toString()
Missing semicolon

2023-08-25 15:30 UTC, NexusKitten commented on extensions/LIZARD_OFFICIAL/2FA.js
> +            text: "GET TOTP CODE [CODE]",
This is more of a nitpick, but to parody blocks in Scratch it's preferred to use lowercase for your blocks unless necessary.

2023-08-25 15:30 UTC, NexusKitten commented on extensions/LIZARD_OFFICIAL/aes.js
> +/* eslint-disable */
Same thing here about `/* eslint-disable */`, see previous comment pertaining to it.

2023-08-25 15:30 UTC, NexusKitten commented on extensions/LIZARD_OFFICIAL/aes.js
> +      return CryptoJS.AES.encrypt(args.TEXT,args.KEY).toString()
Missing semicolon

2023-08-25 15:30 UTC, NexusKitten commented on extensions/LIZARD_OFFICIAL/aes.js
> +        id: 'AES',
The extension ID should contain someway to identify it's made by you. Something like "aeslizard" would work.

2023-08-26 17:00 UTC, LIZARD-OFFICIAL commented
> Some other finishing comments:
> 
> * Both extensions need to start with the metadata the other extensions do- see [CONTRIBUTING.md](https://github.com/TurboWarp/extensions/blob/master/CONTRIBUTING.md).
> * Consider documentation for one or both of these extensions, as both of thier purposes are rather complex and may be confusing to other audiences.

Did all of them, working on documentation rn.

2023-08-26 17:33 UTC, LIZARD-OFFICIAL commented
@GarboMuffin please merge, its finished.

2023-08-26 17:40 UTC, LIZARD-OFFICIAL commented
> > > > It would help if you could separate these two extensions into separate pull requests, so we can review them individually.
> > > 
> > > 
> > > I can't create two forks of same repo
> > 
> > 
> > Use [branches.](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository)
> 
> Also, don't use the `master` branch for pull requests.

Which one do i use then?

2023-08-26 17:53 UTC, LIZARD-OFFICIAL commented
I'm gonna close this and open a new one with `cryptography` branch

2023-08-26 17:53 UTC, closed without merging